import Header from "@/components/header/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PromotionHeader from "@/components/header/PromotionHeader";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { cn } from "@/lib/utils";
import Nav from "@/components/header/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Uplabs clone",
  description: "Generated by Uplabs clone",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div>
            <PromotionHeader />
            <Header />
         
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
